sequenceDiagram
    autonumber
    actor USR as User
    participant FE as FE Server
    participant BE as BE Server
    participant DB as Database

    USR ->> FE: Request create user page
    activate FE
    note over USR, DB: BASE OF REQUEST DIAGRAM
    FE ->> BE: GET create user page
    activate BE
    BE ->> DB: Get role data from database
    activate DB
    alt Role not found
        DB -->> BE: Return HTTP 200 <br> with NULL
        BE -->> FE: Return HTTP 200 <br> with NULL
        FE -->> USR: Return render without role checkbox
    else Role found
        DB -->> BE: Return HTTP 200 <br> with objects
        deactivate DB
        BE -->> FE: Return HTTP 200 <br> with objects
        deactivate BE
        FE -->> USR: Return render with role checkbox
    end
    USR ->> FE: User submit form
    deactivate FE
    note over USR, DB: ACTION POST DIAGRAM